= TP Étude de Cas : Coopain
:author: Professeur Agrégé d'Informatique
:revnumber: 1.0
:toc: left
:toc-title: Sommaire
:icons: font
:description: Préparation à l'E5 - BTS SIO SLAM 2ème année


== Mission 1 – Gestion des demandes d'insémination

**Question 1.1 :** Déduire de la requête SQL fournie dans le dossier documentaire (**Document 2**), la règle de gestion utilisée par Coopain pour choisir une paillette lors d'une demande d'insémination.

**Réponse :**

la règle de gestion utilisée par Coopain permet d’utiliser en priorité les paillettes issues des Taureau  les plus anciennes afin d’assurer une bonne gestion du stock.

***

**Question 1.2 :** Indiquer pour chaque information à imprimer sur une paillette (**Document 3**), la ou les données nécessaires en précisant pour chacune d'où elle provient dans le schéma existant et si elle nécessite une transformation.

**Réponse :**

oui la Date de collecte est transformée et provient de la table Collecte et une donnée de source date

non le N° d’agrément du CCS n’est pas transformé et ne provient d’aucune table (donnée constante)

non le N° national d’identification du taureau n’est pas transformé et provient de la table Taureau et une donnée de source idNational

oui le Code-barres est transformé et provient des tables Taureau, Collecte et Lot et des données de source numeroIE, date et numero

non le N° IE du taureau n’est pas transformé et provient de la table Taureau et une donnée de source numeroIE

oui le Quantième de la date de collecte est transformé et provient de la table Collecte et une donnée de source date

non le Numéro de lot n’est pas transformé et provient de la table Lot et une donnée de source numero

non le Code de la race n’est pas transformé et provient de la table Taureau et une donnée de source codeRace

non le Nom du taureau n’est pas transformé et provient de la table Taureau et une donnée de source nom

***

**Question 1.3 :** Écrire la requête permettant d'obtenir pour le taureau FR0103015562 les tarifs des types de paillette (libellé du type de paillette, prix de la paillette).

**Réponse :**
[source,sql]
----
SELECT libelle, prixPaillette
FROM TypePaillette, Tarif
WHERE Tarif.idTypePaillette = TypePaillette.id
AND idNationalTaureau = 'FR0103015562';
----

***

**Question 1.4 :** Écrire la requête permettant d'obtenir la liste des taureaux (identifiant national, nom, stock total restant de paillettes), le tout trié de façon croissante par stock total restant.

**Réponse :**

[source,sql]
----
SELECT idNational, nom,
(
    SELECT SUM(stockRestant)
    FROM Lot
    WHERE Lot.idNationalTaureau = Taureau.idNational
) AS stockTotal
FROM Taureau
ORDER BY stockTotal ASC;
----

***

